name: Deploy CDK Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Install CDK dependencies
        run: pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install Lambda dependencies and upload to S3
        run: |
          cd lambda
          find . -mindepth 1 -maxdepth 1 ! -name '*.py' ! -name 'requirements.txt' ! -name 'routers' -exec rm -rf {} +
          pip install -r requirements.txt -t .
          zip -r ../lambda.zip .
          cd ..
          aws s3 cp lambda.zip s3://mango-shared-bucket-${{ secrets.AWS_ACCOUNT_ID }}/lambda.zip

      - name: Deploy CDK stack
        run: cdk deploy --require-approval never --no-asset-metadata
      
      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name Seng3011MangoCdkStack-MainFunctionE9DD22DA-68j4sdpsXpiN \
            --s3-bucket mango-shared-bucket-${{ secrets.AWS_ACCOUNT_ID }} \
            --s3-key lambda.zip